{
 "title": "Jenkins Cluster Copy",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Processing speed",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "rate(jenkins_job_building_duration_count[1m])"
    }
   ]
  },
  {
   "title": "Job queue duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 4, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "jenkins_job_queuing_duration" }
   ]
  },
  {
   "title": "Queued rate",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "rate(jenkins_job_queuing_duration_count[1m])"
    }
   ]
  },
  {
   "title": "JVM free memory",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 4 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(vm_memory_total_max{job=\"jenkins\"} - vm_memory_total_used{job=\"jenkins\"}) / vm_memory_total_max{job=\"jenkins\"} * 100.0"
    }
   ]
  },
  {
   "title": "JVM uptime",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 7 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "expr": "vm_uptime_milliseconds{job=\"jenkins\"}"
    }
   ]
  },
  {
   "title": "Jenkins health",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "jenkins_health_check_score" }
   ]
  },
  {
   "title": "Build Status",
   "type": "heatmap",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "default_jenkins_builds_last_build_result"
    }
   ]
  },
  {
   "title": "Executor free",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "jenkins_executor_free_value" }
   ]
  },
  {
   "title": "Number of Jobs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "jenkins_job_count_value" }
   ]
  },
  {
   "title": "Installed Plugins",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "jenkins_plugins_active" }
   ]
  },
  {
   "title": "Executor In-use",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 13 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "jenkins_executor_in_use_value" }
   ]
  },
  {
   "title": "Jenkins plugins failed",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 13 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "jenkins_plugins_failed" }
   ]
  },
  {
   "title": "Resource usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 13 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "vm_cpu_load{job=\"jenkins\"}"
    }
   ]
  },
  {
   "title": "Jenkins queue size",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 16 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "jenkins_queue_size_value" }
   ]
  }
 ]
}